# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.
ENV["RAILS_ENV"] ||= "test"

require 'cucumber/rails'
require 'cucumber/rspec/doubles'
require 'pry'
require 'capybara/poltergeist'
require File.expand_path("../../../config/environments/test.rb",  __FILE__)
require 'webmock/cucumber'
require_relative '../../spec/support/factory_girl'
WebMock.disable_net_connect!(allow_localhost: true)

ActionController::Base.allow_rescue = false

Before do
  begin
    DatabaseCleaner.strategy = :transaction
  rescue NameError
    raise "You need to add database_cleaner to your Gemfile (in the :test group) if you wish to use it."
  end

  Timecop.freeze
  Warden.test_mode!
  Mail.defaults { delivery_method :test }
end

After do |scenario|
  Timecop.return
  Warden.test_reset!
  if scenario.failed? && Capybara.current_driver == :poltergeist
    desc = scenario.name
    filename = desc.downcase.split(/(?<=.)\.(?=[^.])(?!.*\.[^.])/m)
    filename.map! { |s| s.gsub(/[^a-z0-9\-]+/i, '_') }
    STDERR.puts "\n\n\n----------
                 Screenshot saved at #{page.save_screenshot("tmp/capybara/#{filename.join('.')}.png", full: true)}
                 \n------------\n"
  end
end

# Possible values are :truncation and :transaction
# The :transaction strategy is faster, but might give you threading problems.
# See https://github.com/cucumber/cucumber-rails/blob/master/features/choose_javascript_database_strategy.feature
Capybara.configure do |config|
  config.javascript_driver = :poltergeist
  config.default_driver = :rack_test
end

Dir[Rails.root.join("features/support/**/*.rb")].each { |f| require f }
World(WaitForAjax)
World(FactoryGirl::Syntax::Methods)
World(Warden::Test::Helpers)
