AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Documentation:
  Enabled: false

Style/SingleLineMethods:
  Exclude:
    - 'app/models/contact.rb'
