default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: rhit_triangle

development:
  <<: *default
  database: rhit_triangle_dev

test: &test
  <<: *default
  database: rhit_triangle_test

production:
  <<: *default
  database: rhit_triangle_prod

cucumber:
  <<: *test
